
services:
  pwsh:
    build: .
    image: pwsh:7.6.0

    container_name: powershell
    entrypoint: ["pwsh"]
    #command: sleep infinity
    tty: true
    stdin_open: true
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /mnt:/mnt:rw
    working_dir: /mnt/tank0/apps/stacks/bootstrap
    restart: unless-stopped
# modo consola
#docker compose run pwsh
# modo script
#docker compose run pwsh ./job.ps1
