services:
  worker:
    image: ghcr.io/bonzosoft/pwsh:latest
    working_dir: ${PWD}
    #entrypoint: ["pwsh"]
    stdin_open: true
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc:/host/etc:ro
      - /mnt:/mnt:rw
      - ${PWD}/.config/gh:/root/.config/gh