#!/bin/bash

### ERROR MANAGEMENT ###########################################################

set -euo pipefail

function trap_error {
    printf "[ERRO]\t An unexpected error has ocurred. Exiting...\n"
}

trap trap_error ERR

### END ERROR MANAGEMENT #######################################################


GH_BINARY="./bin/gh"
GH_VERSION="2.88.1"
GH_CONFIGDIR="/tmp/gh-config"
ORGANIZATION="bonzosoft"
COMMON="common-tools"

### FUNCTIONS ##################################################################

function main {    
    command=""
    target=""
    for param in "${@}"; do
        case "${param}" in
            "login")
                command="gh_login"
                ;;
            "logout")
                command="gh_logout"
                ;;
            "pull")
                command="gh_pull"
                ;;
            "start")
                command="compose_start"
                ;;
            "stop")
                command="compose_stop"
                ;; 
            *)
                printf "[ERRO]\t Unknow parameter '%s'.\n" "${param}"
                return 1
                ;;
        esac
    done

    if [[ -z ${command} ]]; then
        printf "[ERRO]\ A valid command parameter must be provided.\n"
    fi

    if [[ ! -x ${GH_BINARY} ]]; then
        gh_download
    fi

    case "${command}" in
        "start"|"stop"|"pull")
            if [[ -z "${target}" ]]; then
                printf "[ERRO]\t Missing target for action.\n" 
                return 1
            else
                "${command}" "${target}"
            fi
            ;;
        *)
            if [[ -z "${target}" ]]; then
                "${command}"
            else
                printf "[ERRO]\t Invalid argument '%s'.\n" "${target}"
                return 1
            fi
            ;;
    esac
}

function gh_check {
    local binary=${GH_BINARY}
    local configdir=${GH_CONFIGDIR}

    # validation
    if [[ -z "${binary}" ]]; then
        printf "[ERRO]\t 'GH' path not defined.\n"
        return 1
    fi

    if [[ ! -x "${binary}" ]]; then
        printf "[ERRO]\t 'GH' binary not found.\n"
        return 1
    fi

    if [[ -z "${configdir}" ]]; then
        printf "[ERRO]\t GH config directory not defined.\n"
        return 1
    fi

    return 0
}

function gh_download {
    printf "[INFO]\t Downloading 'GH'.\n"

    local binary=${GH_BINARY}
    local version=${GH_VERSION}
    local tempfile=$(mktemp)

    # validation
    if [[ -z "${GH_BINARY}" ]]; then
        printf "[ERRO]\t 'GH' path not defined.\n"
        return 1
    fi

    if [[ -z "${version}" ]]; then
        printf "[ERRO]\t 'GH' version not defined.\n"
        return 1
    fi

    # logic
    wget --quiet --output-document="${tempfile}" "https://github.com/cli/cli/releases/download/v${version}/gh_${version}_linux_amd64.tar.gz"
    mkdir -p "$(dirname "${binary}")"
    tar --extract --gzip --strip-components=2 --directory="$(dirname "${binary}")" --file="${tempfile}" "gh_${version}_linux_amd64/bin/gh"
    chmod +x "${binary}"
    rm --force "${tempfile}"

    printf "[INFO]\t Success.\n"
    return 0
}

function gh_login {
    printf "[INFO]\t Starting GitHub interactive login.\n"

    local binary=${GH_BINARY}

    # validation
    gh_check

    # logic
    "${binary}" auth login --hostname github.com --git-protocol https --web
    "${binary}" auth setup-git

    printf "[INFO]\t Success.\n"
    return 0
}

function gh_logout {
    printf "[INFO]\t Closing GitHub session.\n"

    local configdir=${GH_CONFIGDIR:?}
    
    # logic
    if [[ -d "${configdir}" ]]; then
        rm --recursive --force "${configdir}" > /dev/null
    fi

    printf "[INFO]\t Success.\n"
    return 0
}

function gh_pull {
    printf "[INFO] Pulling GitHub repository.\n"

    local binary=${GH_BINARY}
    local organization=${ORGANIZATION:?}
    local name=$1
    local branch=${2:-main}

    # validation
    gh_check

    if [[ -z "${name}" ]]; then
        printf "[ERRO]\t Repository name must be provided.\n"
        return 1
    fi

    # logic
    if [[ ! -d "${name}" ]]; then
        printf "[INFO]\t Initializing repository '%s'.\n" "${name}"

        "${binary}" repo clone "${organization}/${name}" "./${name}" > /dev/null # 2>&1
    fi

    printf "[INFO]\t Updating repository '%s'.\n" "${name}"

    pushd "./${name}" > /dev/null
    "${binary}" repo sync --branch "${branch}" --force > /dev/null # 2>&1
    git submodule update --init --recursive > /dev/null # 2>&1
    popd > /dev/null

    printf "[INFO]\t Success.\n"
    return 0
}

function compose_start {
    gh_pull
}

function compose_stop {

}
### END FUNCTIONS ##############################################################

main "${@}"