#!/bin/bash

### ERROR MANAGEMENT ###########################################################

set -euo pipefail

function trap_errorr {
    printf "[\033[31mERRO\033[0m]\t An unexpected error has ocurred. Exiting...\n"
}

trap trap_error ERR

### END ERROR MANAGEMENT #######################################################


GH_BINARY="./bin/gh"
GH_VERSION="2.88.1"
GH_CONFIGDIR="/tmp/gh-config"
ORGANIZATION="bonzosoft"
COMMON="common-tools"
PREDEPLOY="predeploy"

### FUNCTIONS ##################################################################

function main {    
    local param1="${1:?A command must be provided.}"
    local param2="${2:-}"

    if [[ ! -x "${GH_BINARY}" ]]; then
        gh_install
    fi

    case "${param1}" in
        "login")
            gh_login
            ;;
        "logout")
            gh_logout
            ;;
        "install")
            gh_install
            ;;
        *)
            case "${param2}" in
                "pull")
                    gh_pull "${param1}"
                    ;;
                "start")
                    compose_start "${param1}"
                    ;;
                "stop")
                    compose_stop "${param1}"
                    ;;
                *)
                    printf "[\033[31mERRO\033[0m]\t Unknown parameter combination.\n"
                    return 1
                    ;;
            esac
            ;;
    esac

    return 0
}

function gh_check {
    local binary=${GH_BINARY}
    local configdir=${GH_CONFIGDIR}

    # validation
    if [[ -z "${binary}" ]]; then
        printf "[\033[31mERRO\033[0m]\t 'GH' path not defined.\n"
        return 1
    fi

    if [[ ! -x "${binary}" ]]; then
        printf "[\033[31mERRO\033[0m]\t 'GH' binary not found.\n"
        return 1
    fi

    if [[ -z "${configdir}" ]]; then
        printf "[\033[31mERRO\033[0m]\t GH config directory not defined.\n"
        return 1
    fi

    return 0
}

function gh_install {
    printf "[\033[33mINFO\033[0m]\t Preparing the environment for 'GH'.\n"

    local binary=${GH_BINARY:?}
    local version=${GH_VERSION:?}
    local common=${COMMON:?}
    local tempfile=$(mktemp)
    
    # validation

    # logic
    printf "[\033[33mINFO\033[0m]\t Downloading 'GH'.\n"
    wget --quiet --output-document="${tempfile}" "https://github.com/cli/cli/releases/download/v${version}/gh_${version}_linux_amd64.tar.gz"
    mkdir -p "$(dirname "${binary}")"
    tar --extract --gzip --strip-components=2 --directory="$(dirname "${binary}")" --file="${tempfile}" "gh_${version}_linux_amd64/bin/gh"
    chmod +x "${binary}"
    rm --force "${tempfile}"

    printf "[\033[33mINFO\033[0m]\t Downloading '%s'.\n" "${common}"
    gh_pull "${common}"
    #git clone "https://github.com/${ORGANIZATION}/${common}.git" "${common}"


    printf "[\033[33mINFO\033[0m]\t Success.\n"
    return 0
}

function gh_login {
    printf "[\033[33mINFO\033[0m]\t Starting GitHub interactive login.\n"

    local binary=${GH_BINARY:?}

    # validation
    gh_check

    # logic
    "${binary}" auth login --hostname github.com --git-protocol https --web
    "${binary}" auth setup-git

    printf "[\033[33mINFO\033[0m]\t Success.\n"
    return 0
}

function gh_logout {
    printf "[\033[33mINFO\033[0m]\t Closing GitHub session.\n"

    local configdir=${GH_CONFIGDIR:?}
    
    # logic
    if [[ -d "${configdir}" ]]; then
        rm --recursive --force "${configdir}" > /dev/null
    fi

    printf "[\033[33mINFO\033[0m]\t Success.\n"
    return 0
}

function gh_pull {
    printf "[\033[33mINFO\033[0m]\t Pulling GitHub repository.\n"

    local binary=${GH_BINARY}
    local organization=${ORGANIZATION:?}
    local name=$1
    local branch=${2:-main}

    # validation
    gh_check

    if [[ -z "${name}" ]]; then
        printf "[\033[31mERRO\033[0m]\t Repository name must be provided.\n"
        return 1
    fi

    # logic
    if [[ ! -d "${name}" ]]; then
        printf "[\033[33mINFO\033[0m]\t Initializing repository '%s'.\n" "${name}"

        "${binary}" repo clone "${organization}/${name}" "./${name}" > /dev/null # 2>&1
    fi

    printf "[\033[33mINFO\033[0m]\t Updating repository '%s'.\n" "${name}"

    pushd "./${name}" > /dev/null
    "../${binary}" repo sync --branch "${branch}" --force > /dev/null # 2>&1
    git submodule update --init --recursive > /dev/null # 2>&1
    popd > /dev/null

    printf "[\033[33mINFO\033[0m]\t Success.\n"
    return 0
}

function compose_start {
    local name="${1:?}"
    local predeploy="${PREDEPLOY:?}"

    if [[ -d "${name}" ]]; then
        printf "[\033[33mINFO\033[0m]\t Starting '%s'.\n" "${name}"
    else
        printf "[\033[31mERRO\033[0m]\t Target '%s' not available.\n" "${name}"
        return 1
    fi

    pushd "./${name}" > /dev/null
    if [[ -f "./${predeploy}" ]]; then
        bash "./${predeploy}" --realm "prod"
    fi
    docker compose up -d
    #docker compose -p "ix-${name}" up -d
    popd > /dev/null
}

function compose_stop {
    local name="${1:?}"
    
    if [[ -d "${name}" ]]; then
        printf "[\033[33mINFO\033[0m]\t Stopping '%s'.\n" "${name}"
    else
        printf "[\033[31mERRO\033[0m]\t Target '%s' not available.\n" "${name}"
        return 1
    fi

    pushd "./${name}" > /dev/null
    docker compose down
    #docker compose -p "ix-${name}" down
    popd > /dev/null
}
### END FUNCTIONS ##############################################################

main "${@}"